### ISSUE TITLE
Bot circuity 

### ISSUE THREAD

**Issue by taukausanake** [addictgamer/Terrastation-13#19]
So this has bugged me a while. To make a cleanbot/medbot/floorbot all you must do is attack a sensor and robot arm to the item (along with whatever else needed for that bot) and it magically turns into a bot. I don't like that. There's nothing in it that would make it supposedly operate. I want these bots to require a circuit board as their main guts. Something everything interfaces from. It shouldn't be hard to add in the extra part, or to redo the bot as construct-able.
I propose an Adaptive Bot Circuit Board item that can be placed in any of these bots and "adapts" to what the bot is so as to be used with all the bots.

**Comment by addictgamer** [comment]
This issue needs to be re-evaluated for relevance.
