### ISSUE TITLE
Virology

### ISSUE THREAD

**Issue by taukausanake** [addictgamer/Terrastation-13#21]
So it kind of needs to be worked on a bit. It works as it is but needs more to it.

So there's two ways from Bay12 and TG on how to cure a disease. TG uses magic machine that cures an infected blood sample. Bay12 uses radium to make anti-bodies inside the infectees blood. Both seem a little eh... Maybe we can come up with something better. Any ideas?

**Comment by addictgamer** [comment]
This issue needs to be re-evaluated for relevance.
