### ISSUE TITLE
Issues with issues

### ISSUE THREAD

**Issue by Amauros** [addictgamer/Terrastation-13#25]
I would like to point out that all reported issues here are invalid since paradise station was merged into terrastation.  We should close all of them and start fresh, and any issues here should be compared with PS13's issues. Seeing as how their issues are most likely our issues as well, we should check their commits to see if they fixed anything we need fixed.

**Comment by taukausanake** [comment]
How about, oh I don't know, START A NEW REPOSITORY?

**Comment by IceHusky** [comment]
@taukausanake or a new branch...we don't need a whole new repo I don't think.

**Comment by Amauros** [comment]
At this point I want a new repository that uses paradise's code, and then commit what we want from terrastation into it... which as far as I can tell is our custom maps.

In fact, we can probably make a repo JUST for the maps and manually add them and compile with with para's code once they're ready. Any custom code we want to add for our maps can be thrown in a sub folder of the maps and just #INCLUDE them in the .dm

**Comment by Amauros** [comment]
I have a couple ideas on what to do about this, and LZ is trying something as well. Will update when we reach some sort of conclusion.

**Comment by addictgamer** [comment]
Done.
